test

diff --git a/.github/workflows/referesh_token_vsce.yml b/.github/workflows/referesh_token_vsce.yml
--- a/.github/workflows/referesh_token_vsce.yml
+++ b/.github/workflows/referesh_token_vsce.yml
@@ -10,8 +10,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Install jq
+        run: sudo apt-get install jq -y
+
+      - name: Use Node.js version from package.json
+        id: node-version
+        run: echo "NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $GITHUB_ENV
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ env.NODE_VERSION }}
 
       - name: Install dependencies
         run: npm install jsonwebtoken
@@ -19,8 +31,8 @@ jobs:
       - name: Generate GitHub App JWT
         id: jwt
         run: |
-          echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > private-key.pem
           echo "Creating GitHub App JWT..."
+          echo -n "${{ secrets.GH_PRIVATE_KEY }}" > private-key.pem
           node -e "
           const fs = require('fs');
           const jwt = require('jsonwebtoken');
@@ -48,26 +60,36 @@ jobs:
             -H "Authorization: Bearer $JWT" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens | jq -r .token)
-          echo "::set-output name=token::$ACCESS_TOKEN"
           echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
         shell: bash
 
-      - name: Get new VSCE token
-        env:
-          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
+      - name: New VSCE Token
         run: |
-          NEW_VSCE_TOKEN=$(curl -X POST https://marketplace.visualstudio.com/_apis/userentitlements/xyz/refreshToken \
-            -H "Authorization: Basic $VSCE_TOKEN" \
+          echo "Getting new VSCE PAT..."
+
+          # Perform the curl request
+          response=$(curl -s -X POST -u ":$AZURE_DEVOPS_PAT" \
             -H "Content-Type: application/json" \
-            -d '{"some": "payload"}' | jq -r '.token')
+            -d '{ "scopes": "vso.packaging_write vso.packaging_manage vso.drop_manage" }' \
+            "https://dev.azure.com/$AZURE_DEVOPS_ORG/_apis/tokens/pats?api-version=6.0-preview")
 
-          if [ -z "$NEW_VSCE_TOKEN" ]; then
-            echo "Failed to obtain new VSCE token"
-            exit 1
-          fi
+          # Output the response for debugging
+          echo "Response: $response"
 
-          echo "NEW_VSCE_TOKEN=$NEW_VSCE_TOKEN" >> $GITHUB_ENV
-        shell: bash
+          # Check if the response contains an error
+          # if echo "$response" | jq -e .error > /dev/null; then
+          #   echo "Failed to refresh token: $(echo "$response" | jq -r .error)"
+          #   exit 1
+          # fi
+
+          # Extract the new token
+          # new_token=$(echo "$response" | jq -r .pat)
+
+          # Output the new token to the GitHub environment
+          # echo "NEW_VSCE_TOKEN=$new_token" >> $GITHUB_ENV
+        env:
+          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
+          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
 
       - name: Update GitHub Secrets
         run: |
